(require 'recentf)
(require 'recentf-ext)
(defun purge ()
  (recentf-save-list)
  (shell-command "a.out")
  (recentf-load-list))
(defun recentf-purge-tramp-stand-by ()
  (add-hook 'kill-emacs-hook 'purge))
(defun recentf-purge-tramp ()
  (purge))
(provide 'recentf-purge-tramp)
