(require 'recentf)
(require 'recentf-ext)
(defun purge ()
  (recentf-save-list)
  (shell-command (expand-file-name "~/.emacs.d/package.d/recentf-purge-tramp/a.out"))
  (recentf-load-list))
(defun recentf-purge-tramp-stand-by ()
  (add-hook 'kill-emacs-hook 'purge))
(defun recentf-purge-tramp ()
  (purge)
  (recentf-purge-tramp-stand-by))

(provide 'recentf-purge-tramp)
